### ISSUE TITLE
Cannot open the project

### ISSUE THREAD

**Issue by jomsystem-weslylee** [MohithChilakala/React-Native-Template#1]
Unable to resolve "../../App" from "node_modules\expo\AppEntry.js"

**Comment by MohithChilakala** [comment]
> Unable to resolve "../../App" from "node_modules\expo\AppEntry.js"

Not sure where you are getting this error, but App.js is inside src folder so u might need to change path.
You need to change '../../App' to '../../src/App'

I'll update code soon, so that it wont be necessary
